
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MKZ
 */
public class Main extends javax.swing.JFrame
{

    /**
     * Creates new form Main
     */
    public Main()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Bgroup1 = new javax.swing.ButtonGroup();
        Java_radio = new javax.swing.JRadioButton();
        Python_radio = new javax.swing.JRadioButton();
        Matlab_radio = new javax.swing.JRadioButton();
        goster = new javax.swing.JButton();
        diller_combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Combo - Radio Box");

        Bgroup1.add(Java_radio);
        Java_radio.setText("Java");
        Java_radio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Java_radioActionPerformed(evt);
            }
        });

        Bgroup1.add(Python_radio);
        Python_radio.setText("Python");

        Matlab_radio.setText("Matlab");

        goster.setText("Goster");
        goster.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                gosterActionPerformed(evt);
            }
        });

        diller_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dart", "Java Script", "C#", "C++", "C" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Java_radio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Python_radio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Matlab_radio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diller_combo, javax.swing.GroupLayout.Alignment.LEADING, 0, 80, Short.MAX_VALUE)
                    .addComponent(goster, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Java_radio)
                .addGap(18, 18, 18)
                .addComponent(Python_radio)
                .addGap(18, 18, 18)
                .addComponent(Matlab_radio)
                .addGap(18, 18, 18)
                .addComponent(diller_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(goster)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Java_radioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Java_radioActionPerformed
    {//GEN-HEADEREND:event_Java_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Java_radioActionPerformed

    private void gosterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_gosterActionPerformed
    {//GEN-HEADEREND:event_gosterActionPerformed
        String Message = "Seçilen Dil :";
        
        if (Java_radio.isSelected())
        {
            Message += "\n- Java";
        }
        
        if (Python_radio.isSelected())
        {
            Message += "\n- Python";
        }
        
        if (Matlab_radio.isSelected())
        {
            Message += "\n- Matlab";
        }
        
        Message += "\n- " +diller_combo.getSelectedItem();
        
        JOptionPane.showMessageDialog(this, Message);
        
    }//GEN-LAST:event_gosterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Bgroup1;
    private javax.swing.JRadioButton Java_radio;
    private javax.swing.JRadioButton Matlab_radio;
    private javax.swing.JRadioButton Python_radio;
    private javax.swing.JComboBox<String> diller_combo;
    private javax.swing.JButton goster;
    // End of variables declaration//GEN-END:variables
}
