
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MKZ
 */
public class Main extends javax.swing.JFrame
{

    /**
     * Creates new form Main
     */
    public Main()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        girisYap = new javax.swing.JButton();
        JPassword = new javax.swing.JPasswordField();
        JUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        girisYap.setText("Giris Yap");
        girisYap.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                girisYapActionPerformed(evt);
            }
        });
        girisYap.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                girisYapKeyTyped(evt);
            }
        });

        JPassword.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JPasswordActionPerformed(evt);
            }
        });
        JPassword.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                JPasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                JPasswordKeyTyped(evt);
            }
        });

        jLabel1.setText("Kullanıcı Adı :");

        jLabel2.setText("Şifre : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(JUsername)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(girisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addComponent(girisYap)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPasswordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JPasswordActionPerformed
    {//GEN-HEADEREND:event_JPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPasswordActionPerformed

    private void girisYapActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_girisYapActionPerformed
    {//GEN-HEADEREND:event_girisYapActionPerformed
        String username = JUsername.getText();
        String password = new String (JPassword.getPassword());
        String Message;
        boolean login = false;
        
        if (username.equals("Mustafa Zaimoglu") && password.equals("123456"))
        {
            Message = "Hosgeldiniz, " + username;
            login = true;
        }
        else if (!username.equals("Mustafa Zaimoglu") && password.equals("123456"))
        {
            Message = "Kullanıcı Adı Hatalı";
        }
        else if (username.equals("Mustafa Zaimoglu") && !password.equals("123456"))
        {
            Message = "Parola Hatalı";
        }
        else
        {
            Message = "Kullanıcı Adı ve Parola Hatalı";
        }
        
        if (login == true)
        {
            JOptionPane.showMessageDialog(this, Message);
            System.exit(0);
        }
        else
        {
            JOptionPane.showMessageDialog(this, Message);
        }
        
        JUsername.setText("");
        JPassword.setText("");
    }//GEN-LAST:event_girisYapActionPerformed

    private void JPasswordKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JPasswordKeyPressed
    {//GEN-HEADEREND:event_JPasswordKeyPressed
       
    }//GEN-LAST:event_JPasswordKeyPressed

    private void JPasswordKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JPasswordKeyTyped
    {//GEN-HEADEREND:event_JPasswordKeyTyped
    }//GEN-LAST:event_JPasswordKeyTyped

    private void girisYapKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_girisYapKeyTyped
    {//GEN-HEADEREND:event_girisYapKeyTyped
    }//GEN-LAST:event_girisYapKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPassword;
    private javax.swing.JTextField JUsername;
    private javax.swing.JButton girisYap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
