
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MKZ
 */
public class Siparis extends javax.swing.JFrame {

    /** Creates new form Siparis */
    public Siparis() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        menu = new javax.swing.JLabel();
        iskender = new javax.swing.JCheckBox();
        salata = new javax.swing.JCheckBox();
        lahmacun = new javax.swing.JCheckBox();
        ayran = new javax.swing.JCheckBox();
        siparisVer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sipariş Sayfası");

        menu.setText("* MENÜ *");

        iskender.setText("İskender 18 TL");
        iskender.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                iskenderActionPerformed(evt);
            }
        });

        salata.setText("Salata 5 TL");

        lahmacun.setText("Lahmacun 16 TL");

        ayran.setText("Ayran 2 TL");

        siparisVer.setText("Sipariş Ver");
        siparisVer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                siparisVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salata)
                            .addComponent(iskender))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lahmacun)
                            .addComponent(ayran)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(menu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(siparisVer)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(menu)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iskender)
                        .addGap(18, 18, 18)
                        .addComponent(salata))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lahmacun)
                        .addGap(18, 18, 18)
                        .addComponent(ayran)))
                .addGap(29, 29, 29)
                .addComponent(siparisVer)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iskenderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_iskenderActionPerformed
    {//GEN-HEADEREND:event_iskenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iskenderActionPerformed

    private void siparisVerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_siparisVerActionPerformed
    {//GEN-HEADEREND:event_siparisVerActionPerformed
        int ucret = 0;
        String Message = "";
        
        if (iskender.isSelected())
        {
            ucret += 18;
            Message += "\n- İskender";
        }
        
        if (lahmacun.isSelected())
        {
            ucret += 16;
            Message += "\n- Lahmacun";
        }
        
        if (salata.isSelected())
        {
            ucret += 5;
            Message += "\n- Salata";
        }
        
        if (ayran.isSelected())
        {
            ucret += 2;
            Message += "\n- Ayran";
        }
        
        if (ucret > 0)
        {
            Message = "Siparisleriniz : " + Message;
        }
        
        Message =  Message + "\nOdemeniz gereken miktar : " + ucret + " TL";
        
        JOptionPane.showMessageDialog(this, Message);
    }//GEN-LAST:event_siparisVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siparis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siparis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siparis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siparis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siparis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayran;
    private javax.swing.JCheckBox iskender;
    private javax.swing.JCheckBox lahmacun;
    private javax.swing.JLabel menu;
    private javax.swing.JCheckBox salata;
    private javax.swing.JButton siparisVer;
    // End of variables declaration//GEN-END:variables

}
